[package]
name = "interpreter"
version = "0.1.0"
authors = ["Benno van den Berg <bennovandenberg@gmail.com>"]
edition = "2018"

[lib]
name = "monkey"
path = "src/lib.rs"

[[bin]]
name = "repl"
path = "src/bin/repl.rs"

[dependencies]
